In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [2]:
df=pd.read_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data/flats.csv')
df.sample(10)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1278,3 BHK Flat in Sector 65 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,M3M Golfestate4.4 ★,6.15 Crore,"₹ 18,287/sq.ft.",Super Built up area 3363(312.43 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,"Study Room,Servant Room","Sector 65 Gurgaon, Gurgaon, Haryana",23rd of 40 Floors,NaN,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",This lovely 3 bhk apartment/flat in sector 65 ...,"['5 Fan', '1 Exhaust Fan', '5 Geyser', '1 Stov...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of...",H69765162
2397,3 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Signature Global City 92,99 Lac,"₹ 6,622/sq.ft.",Carpet area: 1495 (138.89 sq.m.),3 Bedrooms,2 Bathrooms,3 Balconies,Others,"Sector 92 Gurgaon, Gurgaon, Haryana",1st of 4 Floors,East,0 to 1 Year Old,"['Iris Broadway Mall', 'Pataudi Road', 'Dwarka...",A big fully furnished room in basement,"['5 AC', '1 Modular Kitchen', '1 Chimney', 'No...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Environment5 out of 5', 'Lifestyle4 out of 5...",L69323828
2677,2 BHK Flat in Sector 65 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,M3M Heights,1.9 Crore,"₹ 13,991/sq.ft.",Built Up area: 1358 (126.16 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 65, Sector 65 Gurgaon, Gurgaon, Haryana",40th of 40 Floors,NaN,undefined,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...",Best in class property available at sector 65 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",S68976422
90,2 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global City,1.1 Crore,"₹ 9,838/sq.ft.",Carpet area: 1118 (103.87 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 93, Sector 37D Gurgaon, Gurgaon, Haryana",4th of 4 Floors,South,undefined,"['Sapphire 83 Mall Sector 83', 'Dwarka Express...",Best in class property available at sector 93 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",S68639866
1780,2 BHK Flat in Sector 83 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Vatika Emilia Floors3.7 ★,60 Lac,"₹ 5,714/sq.ft.",Super Built up area 1050(97.55 sq.m.)Built Up ...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Middle Floor, Sector 83 Gurgaon, Gurgaon, Haryana",1st of 2 Floors,South,1 to 5 Year Old,"['Retail Shops', 'Town Square', 'INXT City Cen...",Located in the popular residential address of ...,"['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction4 out of...",U69339966
22,2 BHK Flat in Sector 89 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Gems,86 Lac,"₹ 7,796/sq.ft.",Super Built up area 1103(102.47 sq.m.),2 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sector 89 Gurgaon, Gurgaon, Haryana",4th of 4 Floors,NaN,By 2023,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",We are the proud owners of this 2 bhk apartmen...,[],NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",K68809718
1294,3 BHK Flat in Sector 83 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Emaar Palm Gardens4.1 ★,1.76 Crore,"₹ 9,263/sq.ft.",Super Built up area 1900(176.52 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"704, Sector 83 Gurgaon, Gurgaon, Haryana",6th of 16 Floors,North-West,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",This 3 bhk flat is located in emaar palm garde...,"['3 Wardrobe', '6 Fan', '3 Geyser', '10 Light'...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...",H69976064
1510,3 BHK Flat in Sector 56 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Professors Enclave CGHS,1.54 Crore,"₹ 8,324/sq.ft.",Super Built up area 2000(185.81 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,2 Balconies,"Pooja Room,Servant Room","Sector 56, Sector 56 Gurgaon, Gurgaon, Haryana",6th of 9 Floors,South,10+ Year Old,"['Sector metro station', 'Sector metro station...",This 3 bhk apartment is available for sale in ...,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '12 Lig...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'H...","['Environment4 out of 5', 'Lifestyle5 out of 5...",U69431586
2359,2 BHK Flat in Sector 70A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Capital Residences 360,1.1 Crore,"₹ 7,586/sq.ft.",Super Built up area 1450(134.71 sq.m.),2 Bedrooms,2 Bathrooms,3+ Balconies,NaN,"Sector 70A Gurgaon, Gurgaon, Haryana",8th of 22 Floors,NaN,0 to 1 Year Old,NaN,"Address: 1st floor, sector 70a gurgaon, gurgao...","['2 Geyser', '3 AC', 'No Bed', 'No Chimney', '...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",G69408848
1778,3 BHK Flat in Sector 69 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Tulip Violet4.3 ★,1.4 Crore,"₹ 8,920/sq.ft.",Super Built up area 1568(145.67 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Pooja Room,"12th Floor, Sector 69 Gurgaon, Gurgaon, Haryana",12nd of 14 Floors,East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Looking for a 3 bhk property for sale in gurga...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of...",D69354824

In [3]:
print(df.shape)
df.info()

(3028, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.2+ KB

In [4]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [5]:
df.describe()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
count,3028,3028,3027,3008,3015,3009,3009,3009,3009,1695,3003,3007,2128,3008,2914,3009,2204,2595,2677,3009
unique,405,2881,639,440,2131,1933,7,8,6,50,1288,551,9,49,600,2788,1368,1439,342,2875
top,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,SS The Leaf3.8 ★,1.25 Crore,"₹ 10,000/sq.ft.",Super Built up area 1578(146.6 sq.m.),3 Bedrooms,2 Bathrooms,3 Balconies,Servant Room,"Sohna, Gurgaon, Haryana",2nd of 4 Floors,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Best in class property available at sohna loca...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of...",B68616192
freq,126,2,73,79,19,17,1439,1047,977,630,77,74,506,1479,73,7,367,290,128,2

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.drop(columns=['link','property_id'],inplace=True)
df.sample(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
24,3 BHK Flat in Sector 113 Gurgaon,La Vida by Tata Housing,2.85 Crore,"₹ 12,855/sq.ft.",Super Built up area 2217(205.97 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,Servant Room,"Sector 113 Gurgaon , Gurgaon, Haryana",10th of 25 Floors,East,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
1778,3 BHK Flat in Sector 69 Gurgaon,Tulip Violet4.3 ★,1.4 Crore,"₹ 8,920/sq.ft.",Super Built up area 1568(145.67 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Pooja Room,"12th Floor, Sector 69 Gurgaon, Gurgaon, Haryana",12nd of 14 Floors,East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Looking for a 3 bhk property for sale in gurga...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of..."
1751,3 BHK Flat in Sector 81 Gurgaon,DLF The Ultima4.0 ★,2.5 Crore,"₹ 11,726/sq.ft.",Super Built up area 2132(198.07 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,2 Balconies,Servant Room,"888, Sector 81 Gurgaon, Gurgaon, Haryana",4th of 29 Floors,South-East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",Located in the popular residential address of ...,"['1 Fridge', '6 Fan', '1 Exhaust Fan', '5 Geys...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of..."
998,3 BHK Flat in Sector 79 Gurgaon,Mapsko Mount Ville4.1 ★,1.3 Crore,"₹ 8,024/sq.ft.",Super Built up area 1620(150.5 sq.m.)Carpet ar...,3 Bedrooms,3 Bathrooms,2 Balconies,"Study Room,Pooja Room","Sector 79 Gurgaon, Gurgaon, Haryana",6th of 25 Floors,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This beautiful 3 bhk flat in sector 79 gurgaon...,"['6 Wardrobe', '1 Stove', '1 Chimney', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1917,1 BHK Flat in Sector 56 Gurgaon,Kendriya Vihar4.1 ★,55 Lac,"₹ 9,016/sq.ft.",Carpet area: 610 (56.67 sq.m.),1 Bedroom,2 Bathrooms,1 Balcony,NaN,"Sector 56 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",1 bhk freehold in a well developed area and so...,NaN,"['Power Back-up', 'Security / Fire Alarm', 'In...","['Green Area5 out of 5', 'Construction4 out of..."

In [8]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2053,3 BHK Flat in Sector-33 Sohna,Godrej Nature Plus,1.3 Crore,"₹ 8,349/sq.ft.",Super Built up area 1557(144.65 sq.m.),3 Bedrooms,2 Bathrooms,3+ Balconies,NaN,"Sector-33 Sohna, Gurgaon, Haryana",18th of 22 Floors,North,Within 6 months,"['Signature Global Infinity Mall Sohna', 'Bads...",Bang on nh248 highway. Trusted brand.,NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo...",NaN
1023,4 BHK Flat in Sector 72 Gurgaon,Tata Primanti4.1 ★,5.25 Crore,"₹ 15,648/sq.ft.",Super Built up area 3355(311.69 sq.m.)Built Up...,4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"T7/3003, Sector 72 Gurgaon, Gurgaon, Haryana",30th of 40 Floors,North-East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This lovely 4 bhk apartment/flat in sector 72 ...,"['4 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
178,2 BHK Flat in Sector 68 Gurgaon,Supertech Hues,90 Lac,"₹ 7,627/sq.ft.",Carpet area: 1180 (109.63 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"104, Sector 68 Gurgaon, Gurgaon, Haryana",1st of 35 Floors,East,0 to 1 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Newly constructed property with all the amenit...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Safety5 out of 5', ..."
2028,2 BHK Flat in Sector 2 Gurgaon,HCBS Sports Ville,35 Lac,"₹ 4,375/sq.ft.",Built Up area: 800 (74.32 sq.m.)Carpet area: 6...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sohna Sector 2, Sector 2 Gurgaon, Gurgaon, Har...",8th of 8 Floors,East,1 to 5 Year Old,NaN,Best in class property available at sector 2 s...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...",NaN
57,1 BHK Flat in Sector 84 Gurgaon,Pivotal Devaan,30 Lac,"₹ 6,666/sq.ft.",Carpet area: 450 (41.81 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,NaN,"Sector 84 Gurgaon, Gurgaon, Haryana",14th of 14 Floors,NaN,0 to 1 Year Old,"['Dwarka Expressway', 'RPS International Schoo...",Located in the premium sector 84 this property...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [9]:
df['society'].value_counts()
df['society'].value_counts().shape

(639,)

In [10]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Gems                                     32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Eldeco Accolade3.8 ★                                 24
DLF New Town Heights 13.9 ★                          24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Supertech Araville                                   19
Sare Homes                                           19
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
Sobha City                                           18
Indiabulls Centrum Park3.7 ★                         18
CHD Avenue 713.6 ★                                   18
Conscient Heritage Max4.3 ★                          17
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
Godrej Summit3.7 ★                                   17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
Umang Monsoon Breeze                                 16
HCBS Sports Ville3.6 ★                               16
Godrej Oasis3.9 ★                                    16
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
Ansal Heights 86                                     15
Corona Optus3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ireo Skyon4.0 ★                                      14
MVN Athens3.7 ★                                      14
The Close North4.0 ★                                 14
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Ireo Victory Valley4.1 ★                             14
Ramsons Kshitij3.7 ★                                 14
Vatika The Seven Lamps3.8 ★                          14
Imperia The Esfera                                   14
Orchid Petals4.1 ★                                   14
Indiabulls Enigma                                    14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Ireo The Corridors                                   13
Puri Emerald Bay3.7 ★                                13
SBTL Caladium                                        11
Adani M2K Oyster Grande3.9 ★                         11
Raheja Vedaanta3.6 ★                                 11
Godrej Aria3.8 ★                                     11
Breez Global Hill View                               11
DLF The Skycourt4.2 ★                                11
TARC Maceo3.8 ★                                      11
Alpha Corp GurgaonOne 844.0 ★                        11
M3M Soulitude                                        11
Signature Global Synera3.4 ★                         10
Capital Residences 360                               10
ATS Kocoon                                           10
Pivotal Devaan                                       10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Ramprastha The Edge Towers3.5 ★                      10
Zara Aavaas                                          10
ILD Greens4.1 ★                                      10
Puri Diplomatic Greens4.0 ★                          10
Godrej Air                                           10
DLF New Town Heights 24.0 ★                          10
Pyramid Urban Homes 2                                10
Vatika City4.1 ★                                      9
AIPL The Peaceful Homes3.9 ★                          9
Pareena Mi Casa                                       9
Bestech Park View Sanskruti4.2 ★                      9
Parsvnath Green Ville3.9 ★                            9
Microtek Greenburg3.8 ★                               9
Tulip Ivory3.5 ★                                      8
AVL 36 Gurgaon3.7 ★                                   8
M3M Skycity                                           8
Birla Navya                                           8
ss                                                    8
Emaar Digihomes                                       8
Vatika Lifestyle Homes3.8 ★                           8
Assotech Blith                                        8
The Lions CGHS                                        8
Bestech Altura                                        8
Orris Aster Court Premier                             8
M3M Capital                                           8
GLS Avenue 51                                         8
Signature Andour Heights3.8 ★                         7
Signature Global City                                 7
AIPL Zen Residences                                   7
Ansal Housing Highland Park                           7
Signature Global Orchard Avenue3.6 ★                  7
Trisara Our Homes 3                                   7
Emaar Imperial Gardens3.8 ★                           7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
Orris Carnation Residency3.7 ★                        7
Ireo The Grand Arch4.0 ★                              7
Vipul Lavanya3.9 ★                                    7
Sare Green ParC Phase 3                               7
M3M Sierra 68                                         6
Supertech Hues                                        6
Shapoorji Pallonji Joyville Gurugram                  6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Bestech Park View City4.1 ★                           6
Signature Global Park 4                               6
Signature The Roselia3.6 ★                            6
Pyramid Urban                                         6
Pioneer Araya3.8 ★                                    6
Suncity Vatsal Valley                                 6
Parsvnath Exotica3.7 ★                                6
BPTP Astaire Gardens3.7 ★                             6
Bestech Park View Spa Next4.0 ★                       6
Hero Homes                                            6
Kiran Residency                                       6
Sidhartha NCR One Phase 14.2 ★                        6
Greenopolis                                           6
Mapsko Royale Ville3.7 ★                              6
HSIIDC Sidco Aravali                                  6
Vatika Sovereign Park                                 5
Ireo Uptown4.1 ★                                      5
DLF Park Place4.1 ★                                   5
Central Park Flower Valley Aqua Front Towers          5
Signature Global Grand IVA3.9 ★                       5
Pioneer Park3.8 ★                                     5
Essel Towers                                          5
Satya The Hermitage3.5 ★                              5
Vatika City Homes3.9 ★                                5
Pareena Laxmi Apartments3.6 ★                         5
Green Court3.7 ★                                      5
Emaar MGF Emerald Estate3.8 ★                         5
Conscient Elevate                                     5
Signature Global City 37D Ph 2                        5
Adani Brahma Samsara Vilasa                           5
ATS Marigold                                          5
Krisumi Waterfall Residences                          5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
Tulip Monsella                                        5
Godrej Habitat                                        5
Central Park Resorts4.4 ★                             5
Ashiana Anmol3.5 ★                                    5
Signature Global the Millennia                        5
M3M The Marina4.0 ★                                   5
Silverglades The Melia                                5
Signature Global City 81                              5
Apna Enclave                                          5
Unitech Fresco3.8 ★                                   4
Ramprastha Primera                                    4
Sare Petioles                                         4
Raheja Navodaya3.6 ★                                  4
Unitech Vistas                                        4
Ramprastha Skyz                                       4
Prime Habitat                                         4
Lotus Homz4.0 ★                                       4
Corona Gracieux                                       4
Godrej Frontier3.7 ★                                  4
Tata Gurgaon Gateway3.8 ★                             4
Krrish Provence Estate                                4
Emaar Palm Heights                                    4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
DLF The Skycourt                                      4
Signature The Serenas                                 4
Godrej Icon                                           4
Orris Aster Court                                     4
SS The Coralwood3.4 ★                                 4
ILD Grand                                             4
Railway Officers RPF Society                          4
Global Hill View                                      4
Pivotal Riddhi Siddhi                                 3
Spaze Privvy The Address3.9 ★                         3
DLF Express Greens3.9 ★                               3
Whiteland Blissville                                  3
Sukhshanti Apartment                                  3
AIPL Club Residences                                  3
DLF The Grove                                         3
Raheja Sampada                                        3
Bestech Park View City 23.9 ★                         3
Shri Banke Bihari Society3.8 ★                        3
Brisk Lumbini Terrace Homes                           3
Tulip Purple                                          3
Unitech Heritage City                                 3
Vatika Independent Floors3.8 ★                        3
Tulip White3.5 ★                                      3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
Guru Gram Haryana CGHS4.1 ★                           3
Unitech The Residences3.7 ★                           3
Raheja Revanta                                        3
DLF Royalton Tower                                    3
AFNHB Jalvayu Vihar3.7 ★                              3
Maxworth City Residences                              3
Sare Green Parc 2                                     3
Essel Tower                                           3
Smriti Apartment                                      3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
DLF Belvedere Towers3.8 ★                             3
Deepak Minda                                          3
Sare Green Parc                                       3
Adani Aangan Arcade                                   3
Vatika Xpressions                                     3
Siddhartha Apartment                                  3
Piedmont Taksila heights3.6 ★                         3
Krrish Florence Estate                                3
Tulip Lemon3.9 ★                                      3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
The Roselia 2                                         3
Shree Arihant Apartment                               3
Conscient Habitat3.6 ★                                3
Mahindra Aura4.2 ★                                    3
Apex Our Homes                                        3
Spaze Privy AT43.9 ★                                  3
Puri Diplomatic Greens3.9 ★                           3
Suncity Platinum Towers                               3
Chintels Paradiso3.9 ★                                3
Valley View Estate                                    3
DLF The Arbour                                        3
Sidhartha NCR Greens4.3 ★                             3
Tulip Petals3.6 ★                                     3
Spaze Privy3.9 ★                                      3
My Home                                               3
Pyramid Elite                                         3
Kendriya Vihar4.1 ★                                   3
Satya Element One                                     3
Shri Ram Apartments                                   3
Unitech Sunbreeze                                     3
Signature Global Solera 2                             3
Sapphire Eighty Three                                 3
DLF Carlton Estate4.0 ★                               3
Unitech Uniworld Gardens3.8 ★                         3
SS Almeria                                            3
Raheja Atharva3.6 ★                                   3
Sidhartha NCR One                                     3
Oriental Valley CHS                                   2
Aqua Front Towers                                     2
Vatika INXT Floors                                    2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
M3M Urbana                                            2
Landmark The Residency                                2
Vasant Appartments                                    2
Raheja Vanya                                          2
Mapsko Paradise3.9 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Park Royal Apartment                                  2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Samaspurkunj                                          2
Residency Grand                                       2
Uphar lakshya homes                                   2
Godrej Aria , sector 79 , Gurgaon                     2
ss residency                                          2
Emaar MGF The Enclave                                 2
Chanderlok Society                                    2
Tulsiani Easy in Homes                                2
Vipul Belmonte3.9 ★                                   2
BPTP Freedom Park Life4.0 ★                           2
Maruti Vihar                                          2
Mahindra Luminare4.0 ★                                2
Ganga Apartment                                       2
Supertech Hill Town                                   2
NBCC Heights3.9 ★                                     2
Mittal Surya Vihar                                    2
Palam Vihar Society                                   2
Ansal Heights3.2 ★                                    2
Supertech Hilltown                                    2
Professors Enclave CGHS                               2
DLF The Crest3.6 ★                                    2
Green Campus CHS                                      2
Today Callidora                                       2
Suncity Avenue 76                                     2
Sahara Grace                                          2
Housing Board Colony                                  2
Godrej Nature Plus Serenity                           2
Ashiana Anmol                                         2
Bestech Spa Signature                                 2
Unitech Uniworld Gardens 23.4 ★                       2
CGHS Airport Apartment                                2
AWHO Shanti Vihar4.0 ★                                2
Central Park 2 Bellevue                               2
Raheja Atlantis3.8 ★                                  2
ROF Aalayas3.8 ★                                      2
Elan The Presidential                                 2
Ansal API Esencia3.7 ★                                2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
Tulip Orange3.9 ★                                     2
M3M Ikonic                                            2
Bestech Park View Sanskruti4.1 ★                      2
Viridian The Plaza 106                                2
Suposhaa Smartworld Orchard                           2
Suncity Heights3.7 ★                                  2
DLF The Icon3.7 ★                                     2
Ansal API Celebrity Suites                            2
Ardee City3.8 ★                                       2
Breeze Global Heights                                 2
Sidhivinayak Apartments                               2
Bhagwati Sadan                                        2
Ramprastha City                                       2
Puri The Aravallis                                    2
Emaar MGF Palm Studios                                2
Signature Global The Millennia 3                      2
M3M Sky Lofts                                         2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
The Penthouses at the Hibiscus                        2
Orchid Island4.2 ★                                    2
SS Hibiscus                                           2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
BPTP Mansions Park Prime                              2
Dlf City                                              2
Silverglades Hightown Residences                      2
Surendra Avenue 69                                    2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Shapoorji Pallonji Joyville                           2
Apartment                                             2
Ambience Caitriona                                    2
Lavanya Apartments                                    2
om appartments                                        2
Paras Irene3.7 ★                                      2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Ansal Sushant Lok CI                                  1

In [11]:
import re
df['society']=df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★',' ',str(name)).strip()).str.lower()

In [12]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
smart world gems                                 32
emaar mgf emerald floors premier                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
la vida by tata housing                          28
signature global solera                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
vatika gurgaon                                   24
experion the heartsong                           24
eldeco accolade                                  24
bestech park view residency                      23
m3m heights                                      22
ats triumph                                      22
emaar palm gardens                               22
tata primanti                                    22
sare crescent parc                               21
rof ananda                                       21
godrej                                           21
experion windchants                              20
sare homes                                       19
supertech araville                               19
antriksh heights                                 19
hcbs sports ville                                18
sobha city                                       18
chd avenue                                       18
m3m golfestate                                   18
indiabulls centrum park                          18
mapsko mount ville                               18
ats tourmaline                                   18
ambience creacions                               18
m3m skywalk                                      18
gls arawali homes                                17
godrej summit                                    17
conscient heritage max                           17
pareena coban residences                         17
godrej oasis                                     16
umang monsoon breeze                             16
bestech park view grand spa                      16
m3m merlin                                       16
corona optus                                     15
ramsons kshitij                                  15
ansal heights 86                                 15
dlf the skycourt                                 15
emaar mgf the palm drive                         15
umang winter hills                               14
indiabulls enigma                                14
mvn athens                                       14
imperia the esfera                               14
orchid petals                                    14
ireo victory valley                              14
vatika the seven lamps                           14
bestech park view ananda                         14
the close north                                  14
dlf the primus                                   14
ireo skyon                                       14
puri emerald bay                                 13
central park flower valley                       13
puri diplomatic greens                           13
ireo the corridors                               13
ats kocoon                                       13
tarc maceo                                       11
m3m soulitude                                    11
godrej aria                                      11
breez global heights                             11
bestech park view sanskruti                      11
alpha corp gurgaonone                            11
raheja vedaanta                                  11
ild greens                                       11
breez global hill view                           11
dlf regency park                                 11
adani m2k oyster grande                          11
sbtl caladium                                    11
zara aavaas                                      10
pyramid urban homes 2                            10
capital residences 360                           10
emaar mgf palm hills                             10
godrej air                                       10
signature global synera                          10
ramprastha the edge towers                       10
pivotal devaan                                   10
parsvnath green ville                             9
pareena mi casa                                   9
aipl the peaceful homes                           9
bestech park view city                            9
vatika city                                       9
microtek greenburg                                9
bestech altura                                    8
emaar digihomes                                   8
orris aster court premier                         8
m3m capital                                       8
the lions cghs                                    8
avl 36 gurgaon                                    8
vatika lifestyle homes                            8
tulip ivory                                       8
birla navya                                       8
gls avenue 51                                     8
assotech blith                                    8
ss                                                8
m3m skycity                                       8
ashiana anmol                                     7
orris carnation residency                         7
vipul lavanya                                     7
signature andour heights                          7
signature global city                             7
ansal housing highland park                       7
signature global orchard avenue                   7
ireo the grand arch                               7
mapsko casa bella                                 7
emaar imperial gardens                            7
sidhartha ncr one phase                           7
trisara our homes 3                               7
sare green parc phase 3                           7
aipl zen residences                               7
sare crescent parc royal greens phase 1           7
signature global city 63a                         6
pyramid urban                                     6
green court                                       6
signature the roselia                             6
hero homes                                        6
signature global park 4                           6
parsvnath exotica                                 6
suncity vatsal valley                             6
kiran residency                                   6
bestech park view spa next                        6
mapsko royale ville                               6
bptp astaire gardens                              6
supertech hues                                    6
ashiana mulberry                                  6
m3m sierra 68                                     6
pioneer araya                                     6
greenopolis                                       6
hsiidc sidco aravali                              6
unitech fresco                                    5
vatika sovereign park                             5
apna enclave                                      5
pareena laxmi apartments                          5
satya the hermitage                               5
ireo uptown                                       5
signature global grand iva                        5
essel towers                                      5
central park flower valley aqua front towers      5
signature global city 81                          5
vatika city homes                                 5
krisumi waterfall residences                      5
conscient elevate                                 5
tulip monsella                                    5
adani brahma samsara vilasa                       5
pioneer park                                      5
signature global the millennia                    5
emaar mgf emerald estate                          5
ats marigold                                      5
dlf park place                                    5
signature global city 37d ph 2                    5
unitech uniworld gardens                          5
silverglades the melia                            5
godrej habitat                                    5
central park resorts                              5
m3m the marina                                    5
signature global city 92                          5
ramprastha primera                                4
prime habitat                                     4
tata gurgaon gateway                              4
afnhb jalvayu vihar                               4
ss the coralwood                                  4
krrish provence estate                            4
godrej icon                                       4
dlf the arbour                                    4
railway officers rpf society                      4
lotus homz                                        4
essel tower                                       4
emaar palm heights                                4
orris aster court                                 4
ild grand                                         4
global hill view                                  4
unitech vistas                                    4
kendriya vihar                                    4
raheja navodaya                                   4
godrej frontier                                   4
hsiidc sidco shivalik apartments                  4
signature the serenas                             4
ramprastha skyz                                   4
sare petioles                                     4
corona gracieux                                   4
suncity platinum towers                           3
spaze privy at                                    3
sidhartha ncr one                                 3
raheja sampada                                    3
ss residency                                      3
dlf royalton tower                                3
tulip lemon                                       3
spaze privy                                       3
deepak minda                                      3
maxworth city residences                          3
tulip white                                       3
ss almeria                                        3
sukhshanti apartment                              3
unitech sunbreeze                                 3
pivotal riddhi siddhi                             3
unitech heritage city                             3
chintels paradiso                                 3
signature global solera 2                         3
sare green parc                                   3
adani aangan arcade                               3
smriti apartment                                  3
conscient habitat                                 3
pyramid elite                                     3
brisk lumbini terrace homes                       3
the roselia 2                                     3
sidhartha ncr greens                              3
unitech the residences                            3
my home                                           3
valley view estate                                3
satya element one                                 3
bhagwati sadan                                    3
vatika xpressions                                 3
sunischit apartments                              3
guru gram haryana cghs                            3
dlf belvedere towers                              3
aipl club residences                              3
ambience lagoon                                   3
paras quartier                                    3
sapphire eighty three                             3
dlf the grove                                     3
shri ram apartments                               3
tulip petals                                      3
tulip purple                                      3
raheja atharva                                    3
whiteland blissville                              3
spaze privvy the address                          3
piedmont taksila heights                          3
krrish florence estate                            3
dlf carlton estate                                3
mahindra aura                                     3
shri banke bihari society                         3
shree arihant apartment                           3
dlf express greens                                3
sare green parc 2                                 3
vatika independent floors                         3
dhoot time residency                              3
jammu and kashmir bank employees cghs             3
apex our homes                                    3
siddhartha apartment                              3
raheja revanta                                    3
samaspurkunj                                      2
bptp freedom park life                            2
shapoorji pallonji joyville                       2
dlf city                                          2
element one service                               2
breeze global heights                             2
residency grand                                   2
apartment                                         2
om appartments                                    2
lavanya apartments                                2
suncity avenue                                    2
dlf the belaire                                   2
mrg world ultimus                                 2
adani aangan galleria                             2
landmark the residency                            2
mahindra luminare                                 2
signature global the millennia 3                  2
m3m sky lofts                                     2
raheja atlantis                                   2
mapsko paradise                                   2
sahara grace                                      2
orchid island                                     2
rof aalayas                                       2
awho shanti vihar                                 2
sidhivinayak apartments                           2
ansal api esencia                                 2
emaar mgf emerald floors                          2
oriental valley chs                               2
nbcc heights                                      2
supertech hill town                               2
godrej nature plus serenity                       2
ansal heights                                     2
m3m urbana                                        2
suncity avenue 76                                 2
suncity heights                                   2
lagoon apartment                                  2
palam vihar society                               2
maruti vihar                                      2
pioneer urban presidia                            2
m3m latitude                                      2
elan the presidential                             2
the close south                                   2
today callidora                                   2
bptp pedestal                                     2
park royal apartment                              2
central park 2 bellevue                           2
tulip orange                                      2
vasant appartments                                2
shyam apartment                                   2
housing board colony                              2
raheja vanya                                      2
paras irene                                       2
bptp mansions park prime                          2
cghs airport apartment                            2
bestech spa signature                             2
ansal api celebrity suites                        2
green campus chs                                  2
aqua front towers                                 2
ramprastha city                                   2
ardee city                                        2
ramprastha the atrium                             2
shree shyam residency                             2
ganga apartment                                   2
supertech hilltown                                2
vatika inxt floors                                2
mittal surya vihar                                2
suposhaa smartworld orchard                       2
dlf the crest                                     2
tulip leaf                                        2
vatika emilia floors                              2
viridian the plaza 106                            2
professors enclave cghs                           2
dlf the icon                                      2
puri the aravallis                                2
m3m ikonic                                        2
ss hibiscus                                       2
emaar mgf palm studios                            2
the penthouses at the hibiscus                    2
milan cghs 9                                      2
bptp amstoria                                     2
emaar mgf the enclave                             2
vipul belmonte                                    2
surendra avenue 69                                2
ambience caitriona                                2
vipul world floors                                2
silverglades hightown residences                  2
chanderlok society                                2
tulsiani easy in homes                            2
uphar lakshya homes                               2
godrej aria , sector 79 , gurgaon                 2
spire woods now ananda by alpha corp              1
senate court                                      1
signature global orchard avenue 2                 1
the new people apartments                         1
godrej summit premia towers                       1
godrej meridien                                   1
pooja apartment                                   1
gokuldham society, bahadurgarh                    1
4s aradhya homes                                  1
spectrum centre                                   1
vatika india next                                 1
imperia elvedor                                   1
emaar mgf palm terraces                           1
anamika enclave                                   1
huda ashok vihar phase                            1
emaar palm premier                                1
conscient one                                     1
not applicable                                    1
smartworld 1dxp                                   1
czar mahira homes 63a                             1
micasa sec 68                                     1
shyam sadan                                       1
hanumanta apartment                               1
ashiyara 2                                        1
m3m golf hills phase 1                            1
abhinav group housing society                     1
signature signum 95a                              1
aardhya homesh                                    1
pyramid pride                                     1
om apartment dayanand colony                      1
unitech south park                                1
the ivy                                           1
mrg skyline                                       1
m3m one key resiments                             1
sushant lok 1 builder floors                      1
vatika sovereign next sector-82 a gurgaon         1
kanchanjanga tower                                1
millenium bajrang society                         1
adani oyster greens                               1

In [13]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
1.15 Crore          33
50 Lac              33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
40 Lac              29
60 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
1.85 Crore          23
2.35 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
3.4 Crore           14
2.15 Crore          14
2.45 Crore          14
3.25 Crore          13
92 Lac              13
78 Lac              13
1.32 Crore          13
38 Lac              13
2.7 Crore           13
82 Lac              13
5 Crore             12
2.8 Crore           12
1.42 Crore          12
42 Lac              12
1.95 Crore          12
32 Lac              11
25 Lac              11
1.08 Crore          11
Price on Request    11
88 Lac              11
28 Lac              10
87 Lac              10
26 Lac              10
1.78 Crore          10
1.12 Crore          10
1.28 Crore          10
2.55 Crore          10
2.85 Crore           9
3.45 Crore           9
4 Crore              9
1.72 Crore           9
22 Lac               9
36 Lac               9
1.68 Crore           9
2.05 Crore           9
99 Lac               9
56 Lac               8
6 Crore              8
1.76 Crore           8
1.54 Crore           8
6.5 Crore            8
98 Lac               8
86 Lac               8
1.26 Crore           8
1.18 Crore           8
4.25 Crore           8
20 Lac               8
27 Lac               8
48 Lac               8
3.2 Crore            8
2.75 Crore           8
79 Lac               7
1.99 Crore           7
2.9 Crore            7
72 Lac               7
1.02 Crore           7
39 Lac               7
97 Lac               7
3.3 Crore            7
3.7 Crore            7
1.36 Crore           7
46 Lac               7
1.27 Crore           7
1.19 Crore           7
1.29 Crore           7
96 Lac               6
2.95 Crore           6
1.16 Crore           6
37 Lac               6
3.05 Crore           6
3.9 Crore            6
1.51 Crore           6
1.01 Crore           6
21 Lac               6
43 Lac               6
3.35 Crore           6
54 Lac               6
1.39 Crore           6
1.13 Crore           6
1.34 Crore           6
1.07 Crore           6
1.14 Crore           6
71.5 Lac             6
4.1 Crore            6
1.59 Crore           6
1.98 Crore           6
1.49 Crore           6
3.65 Crore           6
5.5 Crore            6
4.5 Crore            5
68 Lac               5
1.62 Crore           5
93 Lac               5
1.92 Crore           5
1.83 Crore           5
64 Lac               5
1.79 Crore           5
24 Lac               5
1.44 Crore           5
1.91 Crore           5
1.69 Crore           5
1.17 Crore           5
2.22 Crore           5
1.24 Crore           5
2.29 Crore           5
66 Lac               5
1.43 Crore           5
1.82 Crore           5
1.93 Crore           5
6.75 Crore           5
2.12 Crore           5
1.33 Crore           5
49 Lac               5
2.78 Crore           5
3.75 Crore           5
29 Lac               5
1.47 Crore           5
67 Lac               4
33 Lac               4
1.23 Crore           4
1.77 Crore           4
3.6 Crore            4
36.5 Lac             4
1.71 Crore           4
2.09 Crore           4
1.22 Crore           4
1.64 Crore           4
5.9 Crore            4
1.66 Crore           4
74 Lac               4
73 Lac               4
89 Lac               4
41.5 Lac             4
28.5 Lac             4
4.3 Crore            4
3.1 Crore            4
7 Crore              4
4.85 Crore           4
31 Lac               4
1.31 Crore           4
1.37 Crore           4
1.52 Crore           4
1.73 Crore           4
58 Lac               4
3.95 Crore           4
6.15 Crore           4
1.58 Crore           4
62 Lac               4
1.48 Crore           4
5.25 Crore           4
5.6 Crore            4
1.63 Crore           3
5.8 Crore            3
72.5 Lac             3
2.01 Crore           3
1.21 Crore           3
2.36 Crore           3
64.5 Lac             3
1.88 Crore           3
1.57 Crore           3
34 Lac               3
51 Lac               3
84 Lac               3
83 Lac               3
2.08 Crore           3
1.09 Crore           3
69 Lac               3
2.03 Crore           3
1.67 Crore           3
2.51 Crore           3
4.8 Crore            3
2.79 Crore           3
2.33 Crore           3
3.8 Crore            3
2.28 Crore           3
1.04 Crore           3
3.49 Crore           3
1.41 Crore           3
91 Lac               3
2.24 Crore           3
3.85 Crore           3
52 Lac               3
3.15 Crore           3
94 Lac               3
47 Lac               3
4.2 Crore            3
4.75 Crore           3
41 Lac               2
4.55 Crore           2
71 Lac               2
87.5 Lac             2
59 Lac               2
11 Crore             2
7.5 Crore            2
27.1 Lac             2
2.04 Crore           2
3.29 Crore           2
1.46 Crore           2
8 Crore              2
8.5 Crore            2
2.13 Crore           2
2.17 Crore           2
1.56 Crore           2
2.26 Crore           2
2.99 Crore           2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
3.21 Crore           2
4.6 Crore            2
2.23 Crore           2
6.2 Crore            2
1.87 Crore           2
3.32 Crore           2
4.26 Crore           2
2.52 Crore           2
4.49 Crore           2
53.5 Lac             2
53 Lac               2
31.5 Lac             2
2.91 Crore           2
77.5 Lac             2
25.5 Lac             2
5.7 Crore            2
2.14 Crore           2
2.58 Crore           2
52.56 Lac            2
27.75 Lac            2
4.7 Crore            2
4.45 Crore           2
88.5 Lac             2
2.02 Crore           2
2.41 Crore           2
14 Crore             2
98.5 Lac             2
56.2 Lac             2
3.55 Crore           2
7.52 Crore           1
95.5 Lac             1
70.85 Lac            1
19 Lac               1
96.07 Lac            1
94.99 Lac            1
86.92 Lac            1
2.86 Crore           1
16 Lac               1
29.99 Lac            1
57 Lac               1
3.72 Crore           1
88.4 Lac             1
4.52 Crore           1
4.16 Crore           1
4.21 Crore           1
8.44 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
32.5 Lac             1
7.8 Crore            1
15 Crore             1
39.5 Lac             1
1.97 Crore           1
4.02 Crore           1
6.25 Crore           1
40.3 Lac             1
82.5 Lac             1
4.95 Crore           1
8.25 Crore           1
3.67 Crore           1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
2.72 Crore           1
49.5 Lac             1
7.9 Crore            1
3.23 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
86.99 Lac            1
87.99 Lac            1
9.2 Crore            1
9.95 Crore           1
85.75 Lac            1
1.86 Crore           1
97.04 Lac            1
1.84 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.53 Crore           1
2.96 Crore           1
61 Lac               1
4.79 Crore           1
55.5 Lac             1
7.56 Crore           1
6.44 Crore           1
1.11 Crore           1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
29.5 Lac             1
94.25 Lac            1
2.97 Crore           1
3.63 Crore           1
3.39 Crore           1
4.67 Crore           1
2.37 Crore           1
95.75 Lac            1
2.98 Crore           1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
price                1
3.19 Crore           1
4.4 Crore            1
4.63 Crore           1
5.31 Crore           1
37.5 Lac             1
2.54 Crore           1
2.69 Crore           1
54.8 Lac             1
31.75 Lac            1
3.98 Crore           1
23 Lac               1
1.06 Crore           1
9.14 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
4.94 Crore           1
10.75 Crore          1
35.5 Lac             1
23.5 Lac             1
3.87 Crore           1
27.5 Lac             1
71.2 Lac             1
54.99 Lac            1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
2.11 Crore           1
24.5 Lac             1
2.82 Crore           1
7.15 Crore           1
11.25 Crore          1
3.79 Crore           1
2.34 Crore           1
6.3 Crore            1
5.49 Crore           1
65.5 Lac             1
2.61 Crore           1
42.5 Lac             1
2.77 Crore           1
20.5 Lac             1
47.5 Lac             1
17.5 Lac             1
90.5 Lac             1
4.86 Crore           1
2.62 Crore           1
5.15 Crore           1
9.3 Crore            1
6.02 Crore           1
1.74 Crore           1
52.5 Lac             1
53.2 Lac             1
29.8 Lac             1
94.5 Lac             1
2.44 Crore           1
9 Crore              1
3.99 Crore           1
64.45 Lac            1
37.1 Lac             1
7.4 Crore            1
3.78 Crore           1
98.88 Lac            1
68.85 Lac            1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [14]:
df['price'].value_counts().shape

(440,)

In [15]:
df.shape

(3028, 18)

In [16]:
df=df[df['price']!='Price on Request']

In [17]:
df.shape

(3017, 18)

In [18]:
def change_in_cr(x):
    # If x is numeric, return as float
    if isinstance(x, (float, int)):
        return x

    # Handle lists (after split)
    if isinstance(x, list):
        if len(x) == 1:  # e.g. ["nan"] or ["2500000.0"]
            try:
                return float(x[0])
            except:
                return None
        elif len(x) >= 2:
            num_str, unit = x[0], x[1]
            try:
                num = float(num_str)
            except:
                return None

            if unit == 'Lac':
                return round(num / 100, 2)
            else:
                return round(num, 2)
        else:
            return None

    # Handle strings (if .str.split not used)
    if isinstance(x, str):
        parts = x.split()
        return change_in_cr(parts)

    return None

In [19]:
df['price']=df['price'].astype(str).str.split(' ').apply(change_in_cr)

In [20]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [21]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip()

In [22]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [23]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
bedRoom          1
Name: count, dtype: int64

In [24]:
df=df[~df['bedRoom'].isnull()]
df=df[df['bedRoom']!='bedRoom']

In [25]:
df['bedRoom']=df['bedRoom'].str.split(' ').str.get(0).astype(int)
df['bathroom']=df['bathroom'].str.split(' ').str.get(0).astype(int)

In [26]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [27]:
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [28]:
df['balcony']=df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [29]:
df['balcony'].value_counts()

balcony
3     974
3+    862
2     749
1     315
0      97
Name: count, dtype: int64

In [30]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [31]:
df['additionalRoom'].fillna('not available',inplace=True)
df['additionalRoom']=df['additionalRoom'].str.lower()

C:\Users\8429s\AppData\Local\Temp\ipykernel_13952\1431783349.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [32]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [33]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
7th   of 14 Floors          35
10th   of 14 Floors         35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
3rd   of 3 Floors           26
2nd   of 2 Floors           26
1st   of 14 Floors          26
5th   of 14 Floors          24
3rd   of 14 Floors          24
8th   of 19 Floors          24
9th   of 14 Floors          23
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 9 Floors           23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
6th   of 18 Floors          18
10th   of 19 Floors         18
7th   of 15 Floors          17
Ground of 1 Floors          17
9th   of 13 Floors          17
10th   of 18 Floors         17
12nd   of 12 Floors         17
7th   of 18 Floors          17
3rd   of 18 Floors          16
5th   of 15 Floors          16
6th   of 12 Floors          15
1st   of 3 Floors           15
2nd   of 12 Floors          15
9th   of 15 Floors          15
6th   of 19 Floors          14
3rd   of 13 Floors          13
6th   of 10 Floors          13
Ground of 4 Floors          13
10th   of 26 Floors         13
1st   of 2 Floors           13
5th   of 5 Floors           13
7th   of 7 Floors           13
10th   of 10 Floors         12
6th   of 15 Floors          12
11st   of 18 Floors         11
17th   of 17 Floors         11
15th   of 19 Floors         11
9th   of 26 Floors          11
9th   of 24 Floors          11
16th   of 19 Floors         11
4th   of 10 Floors          11
6th   of 6 Floors           11
8th   of 8 Floors           11
8th   of 12 Floors          11
4th   of 13 Floors          11
3rd   of 5 Floors           10
2nd   of 19 Floors          10
6th   of 13 Floors          10
1st   of 26 Floors          10
12nd   of 18 Floors         10
7th   of 13 Floors          10
3rd   of 9 Floors           10
4th   of 15 Floors          10
10th   of 12 Floors         10
4th   of 12 Floors          10
7th   of 26 Floors          10
7th   of 21 Floors          10
6th   of 26 Floors           9
14th   of 15 Floors          9
3rd   of 12 Floors           9
7th   of 17 Floors           9
8th   of 15 Floors           9
6th   of 16 Floors           9
7th   of 12 Floors           9
14th   of 19 Floors          9
9th   of 20 Floors           9
18th   of 19 Floors          9
8th   of 22 Floors           9
15th   of 29 Floors          9
5th   of 18 Floors           9
12nd   of 17 Floors          9
13rd   of 14 Floors          9
12nd   of 24 Floors          8
5th   of 13 Floors           8
8th   of 24 Floors           8
9th   of 18 Floors           8
10th   of 13 Floors          8
9th   of 12 Floors           8
2nd   of 5 Floors            8
8th   of 13 Floors           8
5th   of 9 Floors            8
3rd   of 19 Floors           8
2nd   of 8 Floors            8
10th   of 17 Floors          8
3rd   of 15 Floors           8
1st   of 19 Floors           8
2nd   of 15 Floors           8
8th   of 26 Floors           8
12nd   of 19 Floors          8
12nd   of 26 Floors          8
14th   of 24 Floors          8
4th   of 26 Floors           8
11st   of 11 Floors          7
5th   of 20 Floors           7
11st   of 13 Floors          7
7th   of 19 Floors           7
10th   of 21 Floors          7
12nd   of 15 Floors          7
1st   of 13 Floors           7
2nd   of 17 Floors           7
16th   of 16 Floors          7
4th   of 19 Floors           7
2nd   of 13 Floors           7
11st   of 24 Floors          7
2nd   of 10 Floors           7
11st   of 26 Floors          7
5th   of 29 Floors           7
8th   of 10 Floors           7
9th   of 19 Floors           7
8th   of 21 Floors           7
12nd   of 13 Floors          7
13rd   of 13 Floors          7
11st   of 19 Floors          6
1st   of 5 Floors            6
4th   of 17 Floors           6
12nd   of 22 Floors          6
3rd   of 25 Floors           6
6th   of 9 Floors            6
1st   of 10 Floors           6
Ground of 15 Floors          6
14th   of 27 Floors          6
19th   of 19 Floors          6
15th   of 15 Floors          6
7th   of 20 Floors           6
10th   of 20 Floors          6
17th   of 19 Floors          6
Ground of 16 Floors          6
16th   of 18 Floors          6
Ground of 3 Floors           6
10th   of 29 Floors          6
5th   of 10 Floors           6
11st   of 12 Floors          6
5th   of 22 Floors           6
2nd   of 20 Floors           6
10th   of 15 Floors          6
4th   of 18 Floors           6
5th   of 25 Floors           6
18th   of 29 Floors          5
7th   of 8 Floors            5
6th   of 17 Floors           5
7th   of 27 Floors           5
5th   of 8 Floors            5
9th   of 11 Floors           5
12nd   of 29 Floors          5
11st   of 16 Floors          5
9th   of 30 Floors           5
16th   of 26 Floors          5
1st   of 7 Floors            5
5th   of 19 Floors           5
11st   of 30 Floors          5
4th   of 22 Floors           5
9th   of 22 Floors           5
Ground of 19 Floors          5
4th   of 9 Floors            5
10th   of 27 Floors          5
12nd   of 21 Floors          5
8th   of 30 Floors           5
1st   of 12 Floors           5
4th   of 27 Floors           5
6th   of 11 Floors           5
15th   of 18 Floors          5
8th   of 9 Floors            5
14th   of 16 Floors          5
10th   of 25 Floors          5
3rd   of 20 Floors           5
1st   of 15 Floors           5
15th   of 21 Floors          5
Ground of 21 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 28 Floors          5
14th   of 29 Floors          5
6th   of 20 Floors           5
11st   of 25 Floors          5
11st   of 29 Floors          5
14th   of 18 Floors          4
15th   of 32 Floors          4
14th   of 21 Floors          4
22nd   of 24 Floors          4
18th   of 32 Floors          4
13rd   of 21 Floors          4
3rd   of 11 Floors           4
7th   of 11 Floors           4
14th   of 17 Floors          4
3rd   of 22 Floors           4
1st   of 18 Floors           4
8th   of 20 Floors           4
17th   of 26 Floors          4
7th   of 24 Floors           4
15th   of 16 Floors          4
13rd   of 25 Floors          4
15th   of 23 Floors          4
13rd   of 19 Floors          4
Ground of 17 Floors          4
5th   of 23 Floors           4
2nd   of 11 Floors           4
19th   of 40 Floors          4
7th   of 9 Floors            4
11st   of 20 Floors          4
11st   of 15 Floors          4
11st   of 17 Floors          4
19th   of 24 Floors          4
Ground of 13 Floors          4
17th   of 18 Floors          4
14th   of 26 Floors          4
15th   of 26 Floors          4
5th   of 24 Floors           4
15th   of 25 Floors          4
6th   of 30 Floors           4
2nd   of 9 Floors            4
2nd   of 16 Floors           4
12nd   of 16 Floors          4
4th   of 8 Floors            4
7th   of 10 Floors           4
12nd   of 30 Floors          4
22nd   of 30 Floors          4
23rd   of 26 Floors          4
5th   of 16 Floors           4
17th   of 24 Floors          4
20th   of 26 Floors          4
8th   of 16 Floors           4
9th   of 10 Floors           4
17th   of 25 Floors          4
3rd   of 17 Floors           4
3rd   of 10 Floors           4
20th   of 20 Floors          4
25th   of 25 Floors          4
13rd   of 15 Floors          3
15th   of 22 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
3rd   of 26 Floors           3
1st   of 11 Floors           3
15th   of 20 Floors          3
12nd   of 27 Floors          3
5th   of 30 Floors           3
15th   of 40 Floors          3
8th   of 11 Floors           3
23rd   of 23 Floors          3
20th   of 28 Floors          3
Ground of 26 Floors          3
8th   of 17 Floors           3
19th   of 21 Floors          3
6th   of 21 Floors           3
21st   of 22 Floors          3
4th   of 16 Floors           3
4th   of 29 Floors           3
3rd   of 8 Floors            3
24th   of 24 Floors          3
18th   of 18 Floors          3
9th   of 16 Floors           3
26th   of 30 Floors          3
16th   of 20 Floors          3
14th   of 32 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
31st   of 32 Floors          3
27th   of 27 Floors          3
4th   of 21 Floors           3
6th   of 29 Floors           3
17th   of 20 Floors          3
11st   of 27 Floors          3
17th   of 29 Floors          3
19th   of 30 Floors          3
7th   of 23 Floors           3
Ground of 18 Floors          3
9th   of 21 Floors           3
19th   of 29 Floors          3
6th   of 8 Floors            3
15th   of 39 Floors          3
8th   of 40 Floors           3
18th   of 30 Floors          3
5th   of 26 Floors           3
4th   of 20 Floors           3
17th   of 30 Floors          3
2nd   of 26 Floors           3
12nd   of 23 Floors          3
10th   of 28 Floors          3
3rd   of 16 Floors           3
30th   of 32 Floors          3
10th   of 16 Floors          3
10th   of 30 Floors          3
1st   of 35 Floors           3
18th   of 26 Floors          3
6th   of 22 Floors           3
6th   of 23 Floors           3
9th   of 40 Floors           3
8th   of 25 Floors           3
5th   of 17 Floors           3
21st   of 24 Floors          3
1st   of 16 Floors           2
15th   of 45 Floors          2
3rd   of 33 Floors           2
1st   of 17 Floors           2
17th   of 33 Floors          2
10th   of 40 Floors          2
8th   of 32 Floors           2
13rd   of 30 Floors          2
19th   of 27 Floors          2
1st   of 22 Floors           2
8th   of 34 Floors           2
39th   of 40 Floors          2
7th   of 30 Floors           2
8th   of 23 Floors           2
11st   of 23 Floors          2
10th   of 22 Floors          2
2nd   of 28 Floors           2
15th   of 31 Floors          2
7th   of 36 Floors           2
3rd   of 29 Floors           2
9th   of 28 Floors           2
13rd   of 40 Floors          2
43   of 47 Floors            2
6th   of 31 Floors           2
Ground of 23 Floors          2
4th   of 11 Floors           2
2nd   of 25 Floors           2
19th   of 20 Floors          2
18th   of 21 Floors          2
3rd   of 27 Floors           2
10th   of 11 Floors          2
2nd   of 21 Floors           2
15th   of 17 Floors          2
8th   of 28 Floors           2
20th   of 25 Floors          2
10th   of 32 Floors          2
12nd   of 25 Floors          2
4th   of 5 Floors            2
28th   of 30 Floors          2
7th   of 16 Floors           2
Ground of 51 Floors          2
25th   of 30 Floors          2
16th   of 21 Floors          2
1st   of 24 Floors           2
20th   of 22 Floors          2
11st   of 21 Floors          2
14th   of 28 Floors          2
16th   of 27 Floors          2
27th   of 29 Floors          2
13rd   of 20 Floors          2
7th   of 22 Floors           2
2nd   of 40 Floors           2
16th   of 36 Floors          2
5th   of 11 Floors           2
4th   of 34 Floors           2
16th   of 30 Floors          2
7th   of 29 Floors           2
3rd   of 32 Floors           2
8th   of 29 Floors           2
16th   of 32 Floors          2
23rd   of 29 Floors          2
2nd   of 18 Floors           2
2nd   of 7 Floors            2
3rd   of 24 Floors           2
15th   of 24 Floors          2
4th   of 7 Floors            2
17th   of 23 Floors          2
16th   of 34 Floors          2
9th   of 27 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
1st   of 30 Floors           2
1st   of 8 Floors            2
1st   of 20 Floors           2
23rd   of 34 Floors          2
18th   of 24 Floors          2
22nd   of 25 Floors          2
9th   of 17 Floors           2
9th   of 29 Floors           2
25th   of 29 Floors          2
2nd   of 6 Floors            2
24th   of 30 Floors          2
Lower Ground of 4 Floors     2
40th   of 40 Floors          2
14th   of 20 Floors          2
20th   of 23 Floors          2
16th   of 24 Floors          2
2nd   of 24 Floors           2
32nd   of 32 Floors          1
7th   of 25 Floors           1
45   of 47 Floors            1
12nd   of 34 Floors          1
Ground of 25 Floors          1
9th   of 23 Floors           1
26th   of 34 Floors          1
Ground of 24 Floors          1
8th   of 42 Floors           1
21st   of 29 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
9th   of 25 Floors           1
5th   of 34 Floors           1
3rd   of 31 Floors           1
44   of 47 Floors            1
Ground of 40 Floors          1
13rd   of 22 Floors          1
17th   of 47 Floors          1
23rd   of 24 Floors          1
27th   of 48 Floors          1
33rd   of 33 Floors          1
6th   of 7 Floors            1
33rd   of 48 Floors          1
16th   of 35 Floors          1
Ground of 5 Floors           1
18th   of 40 Floors          1
25th   of 36 Floors          1
2nd   of 27 Floors           1
21st   of 28 Floors          1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
32nd   of 55 Floors          1
8th   of 31 Floors           1
20th   of 40 Floors          1
9th   of 42 Floors           1
20th   of 32 Floors          1
Basement of 28 Floors        1
16th   of 51 Floors          1
3rd   of 6 Floors            1
24th   of 27 Floors          1
19th   of 41 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
16th   of 22 Floors          1
20th   of 34 Floors          1
22nd   of 40 Floors          1
18th   of 25 Floors          1
10th   of 51 Floors          1
18th   of 51 Floors          1
20th   of 30 Floors          1
19th   of 22 Floors          1
15th   of 30 Floors          1
19th   of 26 Floors          1
Ground of 11 Floors          1
21st   of 23 Floors          1
29th   of 39 Floors          1
18th   of 20 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
30th   of 34 Floors          1
4th   of 6 Floors            1
15th   of 27 Floors          1
6th   of 25 Floors           1
5th   of 27 Floors           1
19th   of 23 Floors          1
4th   of 25 Floors           1
24th   of 39 Floors          1
30th   of 40 Floors          1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
10th   of 34 Floors          1
3rd   of 40 Floors           1
8th   of 27 Floors           1
17th   of 21 Floors          1
24th   of 32 Floors          1
4th   of 39 Floors           1
28th   of 29 Floors          1
19th   of 31 Floors          1
35th   of 51 Floors          1
2nd   of 36 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
1st   of 44 Floors           1
22nd   of 28 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
17th   of 22 Floors          1
18th   of 22 Floors          1
Basement of 13 Floors        1
Ground of 6 Floors           1
13rd   of 17 Floors          1
20th   of 24 Floors          1
1st   of 6 Floors            1
1st   of 9 Floors            1
5th   of 32 Floors           1
23rd   of 40 Floors          1
12nd   of 32 Floors          1
18th   of 23 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
24th   of 36 Floors          1
2nd   of 34 Floors           1
Basement of 4 Floors         1
28th   of 28 Floors          1
17th   of 31 Floors          1
10th   of 33 Floors          1
18th   of 35 Floors          1
5th   of 35 Floors           1
Ground of 2 Floors           1
13rd   of 18 Floors          1
20th   of 29 Floors          1
7th   of 42 Floors           1
7th   of 34 Floors           1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 6 Floors            1
3rd   of 36 Floors           1
21st   of 41 Floors          1
29th   of 31 Floors          1
10th   of 39 Floors          1
21st   of 26 Floors          1
19th   of 32 Floors          1
16th   of 45 Floors          1
34th   of 34 Floors          1
27th   of 30 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
Ground of 29 Floors          1
14th   of 41 Floors          1
22nd   of 26 Floors          1
4th   of 40 Floors           1
22nd   of 23 Floors          1
5th   of 36 Floors           1
11st   of 22 Floors          1
20th   of 47 Floors          1
7th   of 40 Floors           1
16th   of 41 Floors          1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
31st   of 40 Floors          1
29th   of 29 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [34]:
df['floorNum']=df['floorNum'].str.split(' ').str.get(0).replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [35]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [36]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [37]:
df['facing'].fillna('NA',inplace=True)

C:\Users\8429s\AppData\Local\Temp\ipykernel_13952\3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [38]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [39]:
df['price']=df['price'].astype(float)
df['price_per_sqft']=df['price_per_sqft'].astype(float)

In [40]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [41]:
df.insert(loc=1,column='property_type',value='flat')

In [42]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [43]:
df.to_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/flats_Clean.csv',index=False)

In [44]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
349,2 BHK Flat in Sohna,flat,mvn athens,0.27,5897.0,458.0,Carpet area: 457.81 (42.53 sq.m.),2,2,1,others,"Sector - 5, Sohna, Sohna, Gurgaon, Haryana",4,South-East,1 to 5 Year Old,"['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...",Well connected to national highway like delhi ...,"['1 Bed', '1 Wardrobe', '1 Water Purifier', '3...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
302,2 BHK Flat in Sector 85 Gurgaon,flat,godrej air,1.05,10603.0,990.0,Built Up area: 97 Carpet area: 92 sq.m.,2,2,1,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",15,East,Jan 2024,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...","Vastu compliant, middle floor, facing towards ...",NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Connectivity5 out of 5', 'Lifestyle5 out of ..."
2348,2 BHK Flat in Sector-5 Sohna,flat,mvn athens sohna gurgaon,0.28,5833.0,480.0,Carpet area: 480 (44.59 sq.m.),2,2,1,not available,"Sector-5 Sohna, Gurgaon, Haryana",2,NA,1 to 5 Year Old,NaN,"Near to dam dama lake, lush green and 3km away...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
132,3 BHK Flat in Sector 86 Gurgaon,flat,ansal heights 86,1.25,7396.0,1690.0,Super Built up area 1690(157.01 sq.m.),3,2,1,not available,"Sector 86 Gurgaon, Gurgaon, Haryana",11,NA,0 to 1 Year Old,"['IRIS Broadway Mall', 'Delhi Jaipur Expresswa...",Corner flat on 11th floor ansal heights,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
1137,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.75,8882.0,1970.0,Super Built up area 1970(183.02 sq.m.),4,4,1,not available,"12th Floor, Sector 69 Gurgaon, Gurgaon, Haryana",12,North-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of gurgaon's most sought a...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of..."