In [28]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [29]:
df=pd.read_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/flats_and_house.csv')

In [30]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2280,3 Bedroom House for sale in Sushant Lok Phase 3,house,independent,4.75,28787.0,1650.0,Plot area 1600(148.64 sq.m.)Built Up area: 170...,3,3,3,store room,240 Sq.Yrd Old Siplex 3 Bhk Villa In Gated Blo...,2.0,North-West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",240 sq.Yrd park facing simplex 3 bhk villa for...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '11 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3327,2 BHK Flat in Sector 95 Gurgaon,flat,rof ananda,0.32,5827.0,549.0,Carpet area: 549.16 (51.02 sq.m.),2,2,1,pooja room,"903, Sector 95 Gurgaon, Gurgaon, Haryana",9.0,North,1 to 5 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...",Looking for a 2 bhk property for sale in gurga...,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
1902,4 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,4.00,6666.0,6001.0,Plot area 6000(557.42 sq.m.),4,4,3+,servant room,"B 181, Sector 70A Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Excellently connected via golf course ext. Roa...,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2718,1 Bedroom House for sale in Sector 41 Gurgaon,house,independent,1.65,13750.0,1200.0,Built Up area: 1200 (111.48 sq.m.),1,1,0,not available,"South City I, Sector 41, Gurgaon, Sector 41 Gu...",1.0,NaN,undefined,"['Huda city centre metro station', 'Icici ATM'...",Check out this 2 bhk independent floor for sal...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
2307,5 Bedroom House for sale in DLF Phase 2,house,nul,6.25,34722.0,1800.0,Plot area 200(167.23 sq.m.),5,5,3,"pooja room,servant room","DLF Phase 2, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Vodafone belvedere towers metro station', 'D...",It's an beautiful 5bhk villa at very prime loc...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [31]:
df.shape

(3960, 20)

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3960 entries, 0 to 3959
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3960 non-null   object
 1   property_type    3960 non-null   object
 2   society          3959 non-null   object
 3   price            3940 non-null   float64
 4   price_per_sqft   3940 non-null   float64
 5   area             3940 non-null   float64
 6   areaWithType     3960 non-null   object
 7   bedRoom          3960 non-null   int64
 8   bathroom         3960 non-null   int64
 9   balcony          3960 non-null   object
 10  additionalRoom   3960 non-null   object
 11  address          3949 non-null   object
 12  floorNum         3809 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3959 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3960 non-null   object
 17  furnishDetails   2928 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 618.9+ KB

In [34]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum            151
facing             1176
agePossession         1
nearbyLocations     206
description           0
furnishDetails     1032
features            708
rating              449
dtype: int64

In [35]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [36]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 Bedroom House for sale in Laxman Vihar Phase 2,house,independent,Laxman Vihar Phase 2,0.58,86567.0,67.0,Plot area 67(6.22 sq.m.),2,2,1,"pooja room,others","Laxman Vihar Phase 2, Gurgaon, Haryana",2.0,West,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Near by sec 4 market near by railways station ...,"['1 Fan', '1 Light', '1 Modular Kitchen', 'No ...",['Water Storage'],NaN
1,3 BHK Flat in Sector 77 Gurgaon,flat,emaar mgf palm hills,Sector 77,1.25,8620.0,1450.0,Super Built up area 1450(134.71 sq.m.)Carpet a...,3,4,3,"study room,servant room","Sector 77 Gurgaon, Gurgaon, Haryana",3.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Soh...",Looking for a 3 bhk property for sale in gurga...,"['1 Wardrobe', '1 Geyser', '1 Light', '1 AC', ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,Sector 71,1.00,6734.0,1485.0,Super Built up area 1485(137.96 sq.m.),3,3,3+,not available,"Tower15 Flat No 302, Sector 71 Gurgaon, Gurgao...",3.0,North,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","Ready to move in ,\n , nice view from balcony ...","['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Li...",['Visitor Parking'],"['Green Area5 out of 5', 'Amenities4 out of 5'..."
3,3 BHK Flat in Sector 37C Gurgaon,flat,ild grand,Sector 37C,1.20,6593.0,1820.0,Super Built up area 1820(169.08 sq.m.),3,3,3,not available,"Sector 37C Gurgaon, Gurgaon, Haryana",7.0,NaN,Dec 2023,"['The Esplanade Mall', 'Dwarka Expy, Sector 88...","This 3 bhk flat is located in ild grand, which...",NaN,"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
4,3 BHK Flat in Sector 81 Gurgaon,flat,dlf the ultima,Sector 81,2.20,10461.0,2103.0,Super Built up area 2103(195.38 sq.m.)Built Up...,3,3,3+,"pooja room,study room,servant room,others","E-051, Sector 81 Gurgaon, Gurgaon, Haryana",5.0,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",This beautiful 3 bhk flat in sector 81 gurgaon...,"['1 Water Purifier', '1 Fridge', '5 Fan', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."

In [37]:
df['sector'] = df['sector'].str.lower()

In [38]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 Bedroom House for sale in Laxman Vihar Phase 2,house,independent,laxman vihar phase 2,0.58,86567.0,67.0,Plot area 67(6.22 sq.m.),2,2,1,"pooja room,others","Laxman Vihar Phase 2, Gurgaon, Haryana",2.0,West,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Near by sec 4 market near by railways station ...,"['1 Fan', '1 Light', '1 Modular Kitchen', 'No ...",['Water Storage'],NaN
1,3 BHK Flat in Sector 77 Gurgaon,flat,emaar mgf palm hills,sector 77,1.25,8620.0,1450.0,Super Built up area 1450(134.71 sq.m.)Carpet a...,3,4,3,"study room,servant room","Sector 77 Gurgaon, Gurgaon, Haryana",3.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Soh...",Looking for a 3 bhk property for sale in gurga...,"['1 Wardrobe', '1 Geyser', '1 Light', '1 AC', ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,sector 71,1.00,6734.0,1485.0,Super Built up area 1485(137.96 sq.m.),3,3,3+,not available,"Tower15 Flat No 302, Sector 71 Gurgaon, Gurgao...",3.0,North,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","Ready to move in ,\n , nice view from balcony ...","['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Li...",['Visitor Parking'],"['Green Area5 out of 5', 'Amenities4 out of 5'..."
3,3 BHK Flat in Sector 37C Gurgaon,flat,ild grand,sector 37c,1.20,6593.0,1820.0,Super Built up area 1820(169.08 sq.m.),3,3,3,not available,"Sector 37C Gurgaon, Gurgaon, Haryana",7.0,NaN,Dec 2023,"['The Esplanade Mall', 'Dwarka Expy, Sector 88...","This 3 bhk flat is located in ild grand, which...",NaN,"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
4,3 BHK Flat in Sector 81 Gurgaon,flat,dlf the ultima,sector 81,2.20,10461.0,2103.0,Super Built up area 2103(195.38 sq.m.)Built Up...,3,3,3+,"pooja room,study room,servant room,others","E-051, Sector 81 Gurgaon, Gurgaon, Haryana",5.0,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",This beautiful 3 bhk flat in sector 81 gurgaon...,"['1 Water Purifier', '1 Fridge', '5 Fan', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."

In [39]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 81                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
laxman vihar                                                  27
sector 54                                                     27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 110                                                    16
sushant lok phase 3                                           16
sector 14                                                     15
sector 60                                                     15
sector 63                                                     15
sector 53                                                     14
sector 3                                                      14
gwal pahari                                                   14
sector 52                                                     14
sector 1 imt manesar                                          14
sector 76                                                     14
rajendra park                                                 14
dlf phase 5                                                   14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 39                                                     12
sector 38                                                     12
sector 31                                                     12
uppals southend                                               12
sector 50                                                     12
sector 93                                                     12
sohna road                                                    12
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
south city 1                                                   9
sector 4                                                       9
ashok vihar phase 2                                            9
sector 55                                                      9
sector 95a                                                     9
dwarka expressway                                              8
palam vihar extension                                          8
c block sushant lok phase 1                                    8
sector 40                                                      8
sector 89 a                                                    8
sector 57                                                      8
sector 43                                                      8
malibu town                                                    8
sector 10a                                                     8
sector 59                                                      8
mehrauli  road                                                 8
new colony                                                     7
sector 51                                                      7
sector 11                                                      7
mianwali colony                                                7
sector 26                                                      7
sector 36 sohna                                                7
surat nagar 1                                                  7
sector 58                                                      7
jacobpura                                                      6
rajiv nagar                                                    6
sector 1                                                       6
sector 5                                                       6
jyoti park                                                     6
ashok vihar                                                    6
arjun nagar                                                    5
dayanand colony                                                5
manesar                                                        5
sector 105                                                     5
greenwood city                                                 5
sector 2                                                       5
subhash nagar                                                  5
sector 30                                                      5
saraswati vihar                                                5
ansal plaza                                                    5
sector 80                                                      5
sector 9                                                       5
sector 23a                                                     5
new palam vihar                                                5
chakkarpur                                                     5
sector 28                                                      5
sushant lok phase 2                                            5
imt manesar                                                    4
adarsh nagar                                                   4
vishnu garden                                                  4
krishna colony                                                 4
ravi nagar                                                     4
sector 36                                                      4
new                                                            4
sector 12                                                      4
bhim nagar                                                     4
sector 45                                                      4
baldev nagar                                                   4
dharam colony                                                  4
madanpuri                                                      4
surya vihar                                                    4
sector 3a                                                      4
sector 12a                                                     4
sector 17                                                      4
suncity                                                        4
bhondsi                                                        4
garhi harsaru                                                  4
sector 6                                                       4
devilal colony                                                 4
valley view estate                                             4
shivaji nagar                                                  4
shivpuri                                                       4
sector 15                                                      3
mg road                                                        3
a block sushant lok phase 1                                    3
sector 88b                                                     3
patel nagar                                                    3
shakti nagar                                                   3
prem nagar                                                     3
b block sushant lok phase 1                                    3
laxmi garden                                                   3
sector 17a                                                     3
sector 23                                                      3
maruti kunj                                                    3
sector 17b                                                     3
gandhi nagar                                                   3
sector 110 a                                                   3
sector 27                                                      3
sector 8                                                       3
sector 73                                                      3
lajpat nagar                                                   2
sector 24                                                      2
sheetla colony                                                 2
sector-2 sohna                                                 2
rajiv chowk                                                    2
sector 32                                                      2
golf course ext road                                           2
sector-11 sohna                                                2
mohan nagar                                                    2
acharya puri                                                   2
samaspur                                                       2
daulatabad                                                     2
surat nagar phase 2                                            2
manohar nagar                                                  2
iffco chowk                                                    2
bissar                                                         2
bhawani enclave                                                2
west rajiv nagar                                               2
sohna  road                                                    2
new palam vihar phase 1                                        2
mayfield garden                                                2
rosewood                                                       2
new palam vihar phase 2                                        2
golf course road                                               2
faridabad road                                                 2
sector 15 part 2                                               2
shankar vihar                                                  2
farukhnagar                                                    2
sushant lok                                                    2
hira nagar                                                     2
, delhi ncr                                                    2
sispal vihar                                                   2
ambience island                                                2
block a surya vihar                                            2
surat nagar                                                    2
shanti nagar                                                   2
new basti                                                      2
sector 21                                                      2
sector 41                                                      2
nars                                                           2
sector 15 part 1                                               2
hsiidc plot sector 1 imt manesar                               1
jat colony,fazilpur/taj nagar road                             1
naharpur rupa                                                  1
sector-5 sohna                                                 1
sector 9b                                                      1
laxmna vihar, phase 2                                          1
kanahi                                                         1
om nagar                                                       1
pataudi road                                                   1
heritage city                                                  1
sec 3 bhim vihar part 1 bhimgher kheri                         1
cyber city                                                     1
vir nagar                                                      1
khandsa                                                        1
sector 17c                                                     1
dhankot                                                        1
south city                                                     1
near euro                                                      1
jacobpura near sadar bazar                                     1
alipur                                                         1
tekchand nagar                                                 1
begampur khatola                                               1
saroop garden rajendra park                                    1
near khandsa road                                              1
old delhi road, opp sector-14                                  1
devi lal colony gali no 12 gurgaon nr omkar public school      1
nirvana country pocket h                                       1
lucknow                                                        1
park view                                                      1
bhimgarh kheri phase 3                                         1
new jyoti park                                                 1
sector 5 chowk                                                 1
anand garden, sector-105                                       1
near sector 1 market                                           1
sector 13                                                      1
sai kunj                                                       1
hno 13 sagar enclave sura                                      1
gopal nagar, garhi ghasita, sonipat                            1
part 3 sector 5                                                1
huda saraswati vihar                                           1
urban estate, sector 5                                         1
pratap nagar                                                   1
ats marigold                                                   1
b1 block sector 57                                             1
shivji park colony                                             1
mahalaxmi garden, rajendra place                               1
block h ashok vihar phase iii extension                        1
sector-7 hous                                                  1
civil l                                                        1
v block dlf phase 3                                            1
g block dlf city phase 1                                       1
ansal's palam vihar                                            1
block g sector-57                                              1
near nand hospital                                             1
sector 37a                                                     1
rattan garden                                                  1
sultanpur                                                      1
sector 37b                                                     1
sector 4 urban estate                                          1
damdma                                                         1
sector 21a faridabad                                           1
sector 42                                                      1
udyog vihar phase 1                                            1
ashok vihar phase i                                            1
sector-35 sohna                                                1
carterpuri village                                             1
kheri                                                          1
bhora kalan                                                    1
new colony, sector 7                                           1
rajiv colony                                                   1
sector-5 sheetla colony                                        1
near pataudi chowk                                             1
ashok vihar phase 3                                            1
ram nagar                                                      1
ravi nager basai road                                          1
mahavir pura                                                   1
bptp                                                           1
saraswati enclave                                              1
sadar bazar                                                    1
laxman vihar, railway road,                                    1
godrej aria , sector 79 ,                                      1
garauli kalan                                                  1
Name: count, dtype: int64

In [40]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [41]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [42]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 Bedroom House for sale in Laxman Vihar Phase 2,house,independent,sector 4 phase 2,0.58,86567.0,67.0,Plot area 67(6.22 sq.m.),2,2,1,"pooja room,others","Laxman Vihar Phase 2, Gurgaon, Haryana",2.0,West,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Near by sec 4 market near by railways station ...,"['1 Fan', '1 Light', '1 Modular Kitchen', 'No ...",['Water Storage'],NaN
1,3 BHK Flat in Sector 77 Gurgaon,flat,emaar mgf palm hills,sector 77,1.25,8620.0,1450.0,Super Built up area 1450(134.71 sq.m.)Carpet a...,3,4,3,"study room,servant room","Sector 77 Gurgaon, Gurgaon, Haryana",3.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Soh...",Looking for a 3 bhk property for sale in gurga...,"['1 Wardrobe', '1 Geyser', '1 Light', '1 AC', ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,sector 71,1.00,6734.0,1485.0,Super Built up area 1485(137.96 sq.m.),3,3,3+,not available,"Tower15 Flat No 302, Sector 71 Gurgaon, Gurgao...",3.0,North,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","Ready to move in ,\n , nice view from balcony ...","['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Li...",['Visitor Parking'],"['Green Area5 out of 5', 'Amenities4 out of 5'..."
3,3 BHK Flat in Sector 37C Gurgaon,flat,ild grand,sector 37c,1.20,6593.0,1820.0,Super Built up area 1820(169.08 sq.m.),3,3,3,not available,"Sector 37C Gurgaon, Gurgaon, Haryana",7.0,NaN,Dec 2023,"['The Esplanade Mall', 'Dwarka Expy, Sector 88...","This 3 bhk flat is located in ild grand, which...",NaN,"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
4,3 BHK Flat in Sector 81 Gurgaon,flat,dlf the ultima,sector 81,2.20,10461.0,2103.0,Super Built up area 2103(195.38 sq.m.)Built Up...,3,3,3+,"pooja room,study room,servant room,others","E-051, Sector 81 Gurgaon, Gurgaon, Haryana",5.0,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",This beautiful 3 bhk flat in sector 81 gurgaon...,"['1 Water Purifier', '1 Fridge', '5 Fan', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."

In [43]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 65                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 43                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 112                     24
sector 57                      24
sector 88a                     23
sector 105                     23
sector 33                      23
sector 14                      23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
sector 74                      18
gwal pahari                    18
sector 63a                     18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 60                      15
sector 63                      15
sector 53                      14
sector 1 manesar               14
sector 76                      14
sector 52                      14
sector 55                      14
sector 4 phase 2               13
sector 6                       13
sector 9                       13
sector 36a                     13
sector 46                      13
sector 38                      12
sector 39                      12
sector 31                      12
sohna road road                12
sector 93                      12
sector 3 phase 3 extension     11
sector 9a                      11
sector 41                      11
sector 13                      10
sector 1a manesar              10
manesar                         9
sector 95a                      9
sector 3 phase 2                9
sector 45                       9
sector 2 extension              8
dwarka expressway               8
sector 40                       8
sector 8                        8
sector 17                       8
sector 23                       8
sector 89 a                     8
sector 10a                      8
sector 59                       8
c block sector 43               8
sector 36 sohna road            7
sector 51                       7
sector 58                       7
sector 21                       6
sector 5                        6
sector 1                        6
new sector 2                    5
sector 80                       5
sector 30                       5
sector 23a                      5
new                             4
sector 12a                      4
sector 36                       4
sector 3a                       4
sector 88b                      3
sector 17a                      3
b block sector 43               3
patel nagar                     3
maruti kunj                     3
sector 17b                      3
sector 27                       3
sector 73                       3
sector 15                       3
a block sector 43               3
sector 110 a                    3
Name: count, dtype: int64

In [44]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [45]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [46]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
89,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1209,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1540,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1686,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [47]:
df.loc[89,'sector'] = 'sector 37'
df.loc[1209,'sector'] = 'sector 92'
df.loc[1540,'sector'] = 'sector 90'
df.loc[1686,'sector'] = 'sector 76'

In [48]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
18,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
421,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1997,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3371,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3476,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [50]:
df.loc[[18,421,1997,3371,3476],'sector'] = 'sector 110'

In [51]:
df.shape

(3803, 21)

In [52]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [53]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1642,flat,ansal height 86,sector 86,0.80,5882.0,1360.0,Built Up area: 1360 (126.35 sq.m.),2,2,0,not available,1.0,NaN,undefined,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
2843,flat,central park resorts,sector 48,11.25,28266.0,3980.0,Carpet area: 3980 (369.75 sq.m.),4,5,3+,"pooja room,servant room",2.0,North-West,1 to 5 Year Old,"['Huda Metro Station', 'Omaxe Celebration Mall...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Swimming Poo..."
3801,flat,bestech park view grand spa,sector 81,2.35,8834.0,2660.0,Super Built up area 2660(247.12 sq.m.)Carpet a...,3,4,3+,servant room,6.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, IMT Manesar', 'Dwa...","['5 Wardrobe', '7 Fan', '1 Exhaust Fan', '20 L...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
577,flat,eldeco accolade,sector 33,1.20,8043.0,1492.0,Built Up area: 1492 (138.61 sq.m.)Carpet area:...,2,2,2,study room,NaN,North,0 to 1 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...",NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena..."
3650,flat,unitech sunbreeze,sector 69,0.74,5500.0,1345.0,Super Built up area 1337(124.21 sq.m.),3,3,1,servant room,10.0,NaN,Under Construction,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",[],"['Power Back-up', 'Intercom Facility', 'Lift(s..."

In [55]:
df.to_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/flats_and_house_v1.csv',index=False)